jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

spring:
  application:
    name: auth-service

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_REGISTRATION_ID}
            client-secret: ${GOOGLE_OAUTH_REGISTRATION_SECRET}
            redirect-uri: "http://localhost:8080/oauth2/callback/google-pkce"
        provider:
          google:
            token-uri: https://oauth2.googleapis.com/token
            authorization-uri: https://accounts.google.com/o/oauth2/auth


  datasource:
    url: jdbc:postgresql://localhost:5432/ticket_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration