server:
  port: 8080

spring:
  application:
    name: ticket-service

  datasource:
    url: jdbc:postgresql://ticket-db:5432/ticket_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
